---
language: python
python: "3.11"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages: [python-pip]

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

branches:
  only: [master]
