---
# linux-postinstall handlers

- name: restart timesyncd
  service: name="systemd-timesyncd.service" state="restarted"

- name: load sysctl settings
  command: "/sbin/sysctl -p /etc/sysctl.conf"

- name: reload iptables
  shell: "/sbin/iptables-restore < /etc/network/iptables"

- name: newaliases
  command: newaliases

- name: set hostname
  command: "/sbin/sysctl kernel.hostname={{ hostname }}"

- name: update grub
  command: "/usr/sbin/update-grub"

- name: reload udev
  command: "/sbin/udevadm control --reload-rules"
#  Ubuntu 18.04 error: Failed to reload udev.service: Job type reload
#  is not applicable for unit systemd-udevd.service
#  systemd: name="udev" state="reloaded"

- name: restart udev
  systemd: name="udev" state="restarted"

- name: reload sshd
  systemd: name="{{ lp_service_sshd }}" state="reloaded"
  when: lp_sshd|lower == "yes"

- name: restart bluetooth
  systemd: name="bluetooth" state="restarted"
  when: lp_bluetooth|lower == "yes"

- name: restart gpsd
  systemd: name="gpsd" state="restarted"
  when: lp_gpsd|lower == "yes"

- name: restart postfix
  systemd: name="postfix" state="restarted"
  when: lp_postfix|lower == "yes"

- name: reload postfix
  systemd: name="postfix" state="reloaded"
  when: lp_postfix|lower == "yes"

- name: reload smart
  systemd: name="{{ lp_smart_service_name }}" state="reloaded"
  when: lp_smart|lower == "yes"

- name: apparmor-disable-profile
  shell: apparmor_parser -R /etc/apparmor.d/"{{ apparmor_item_path.stdout }}"

- name: apparmor-enforce-profile
  shell: apparmor_parser -r /etc/apparmor.d/"{{ apparmor_item_path.stdout }}"

- name: reload nfsd
  systemd: name="{{ lp_nfsd_reload_service }}" state="reloaded"
  when: lp_nfsd|lower == "yes"

- name: netplan apply
  shell: netplan apply
  when: lp_netplan|lower == "yes"

- name: create and mount swap file
  shell: sh -c 'dd if=/dev/zero of={{lp_swap_file}} bs=1M count={{lp_swap_size}} && chmod 0600 {{lp_swap_file}} && mkswap {{lp_swap_file}} && swapon {{lp_swap_file}}'

- name: change and mount swap file
  shell: sh -c 'swapoff {{lp_swap_file}} && dd if=/dev/zero of={{lp_swap_file}} bs=1M count={{lp_swap_size}} && chmod 0600 {{lp_swap_file}} && mkswap {{lp_swap_file}} && swapon {{lp_swap_file}}'

- name: remove swap file
  shell: sh -c 'swapoff {{lp_swap_file}} && rm {{lp_swap_file}}'

# EOF
...
