---
# MESSAGES - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- name: Logind message reboot
  ansible.builtin.debug:
    msg: |
      [MESSAGE] Reboot to activate configuration in logind.conf

# MESSAGES - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# EOF
